apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Application
  patch: |-
    - op: replace
      path: /metadata/name
      value: metallb
    - op: replace
      path: /metadata/namespace
      value: core-apps
    - op: replace
      path: /metadata/labels/env
      value: production
    - op: replace
      path: /spec/project
      value: core-apps
    - op: replace
      path: /spec/source/path
      value: manifests/metallb/overlays/prod
    - op: replace
      path: /spec/destination/namespace
      value: metallb-system
    - op: add
      path: /spec/syncPolicy/automated
      value:
        selfHeal: true
        prune: true
    - op: replace
      path: /spec/ignoreDifferences
      value:
      - group: "apiextensions.k8s.io"
        kind: CustomResourceDefinition
        name: bgppeers.metallb.io
        jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
