apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Application
  patch: |-
    - op: replace
      path: /metadata/name
      value: kube-prometheus-stack
    - op: replace
      path: /metadata/namespace
      value: core-apps
    - op: replace
      path: /metadata/labels/env
      value: production
    - op: replace
      path: /spec/project
      value: core-apps
    - op: replace
      path: /spec/source/path
      value: argocd-k8s-resources/kube-prometheus-stack/overlays/prod
    - op: replace
      path: /spec/destination/namespace
      value: monitoring
    - op: add
      path: /spec/syncPolicy/automated
      value:
        selfHeal: true
        prune: true
