apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- overlays/alloy
#- overlays/actions-runner-controller
#- overlays/arc-runner-sets
#- overlays/cert-manager
#- overlays/crossplane
#- overlays/external-secrets
#- overlays/f5-nginx-ingress
#- overlays/fluentbit
#- overlays/kyverno
#- overlays/keda
- overlays/longhorn
- overlays/metallb
- overlays/monitoring
- overlays/redis
- overlays/reloader
#- overlays/sealed-secrets
#- overlays/system-upgrade-controller
#- overlays/tailscale
- overlays/test01
#- overlays/test02-crossplane-azure
#- overlays/test03-crossplane-aws
- overlays/traefik
