apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Application
  patch: |-
    - op: replace
      path: /metadata/name
      value: f5-nginx-ingress
    - op: replace
      path: /metadata/namespace
      value: core-apps
    - op: replace
      path: /metadata/labels/env
      value: production
    - op: replace
      path: /spec/project
      value: core-apps
    - op: replace
      path: /spec/source/path
      value: manifests/f5-nginx-ingress/overlays/prod
    - op: replace
      path: /spec/destination/namespace
      value: nginx-ingress
    - op: add
      path: /spec/syncPolicy/automated
      value:
        selfHeal: true
        prune: true
    - op: add
      path: /spec/syncPolicy/syncOptions/-
      value: "ServerSideApply=true"
    - op: replace
      path: /spec/ignoreDifferences
      value:
      - group: ""
        kind: Service
        jsonPointers:
        - /spec/ports/0/nodePort
        - /spec/ports/1/nodePort
